app = "poke-berry-stats-api"
primary_region = "mad"  # Madrid, puedes cambiar a la región que prefieras

[build]
  image = "davidgg090/poke-berry-stats-api:latest"

[env]
  API_HOST = "0.0.0.0"
  API_PORT = "8000"
  POKEAPI_BASE_URL = "https://pokeapi.co/api/v2"
  POKEAPI_TIMEOUT = "30"
  CACHE_ENABLED = "false"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  path = "/health"
  timeout = "5s"