app = "poke-berry-stats-api"
primary_region = "scl"

[build]
image = "davidgg090/poke-berry-stats-api:latest"

[env]
API_HOST = "0.0.0.0"
API_PORT = "8000"
CACHE_ENABLED = "false"
POKEAPI_BASE_URL = "https://pokeapi.co/api/v2"
POKEAPI_TIMEOUT = "30"

[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 8_000
min_machines_running = 0
processes = [ "app" ]

  [[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  path = "/health"
  timeout = "5s"

[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "1gb"
